### ISSUE TITLE
will this extension support firefox

### ISSUE THREAD

**Issue by arjenzhou** [neaumusic/selection-highlighter#42]
for firefox there is no extension like this, is there any plan to migrate to firefox?

**Comment by neaucode** [comment]
I can probably do this and this is good incentive too :) thank you

**Comment by neaucode** [comment]
just want to post an update that this is actually pretty easy

- I had to use 'options_ui' modal rather than 'options_page' which was weird since firefox doesn't provide extrinsic width/height and I have to hardcode a size for that modal; zooming in/out on the options page triggers a stack overflow of resizing pretty much
- sync.storage.get doesn't work in local development on firefox, even with a gecko id, and prevents the extension from working if not commented out, but it worked fine when I privately published and installed from the store

I need to decide if chrome should also use an option modal or stick with an option page, then just publish

**Comment by arjenzhou** [comment]
Glad to hear that, I will migrate from chrome to firefox as soon as publishing it.

**Comment by neaucode** [comment]
@arjenzhou I just want to mention that I'm heavily working on this and it's relatively stressful; firefox is doing some weird stuff

- when on windows, a double click selects the word with a space in the beginning, hence the 'trimRegex' which keeps the space but strips the actual intended word selection

- on firefox, I'm seeing that in rare cases, a double click has an invisible space added to the selection, which breaks the isUsersSelection offset analysis

- firefox also repeatedly fires the 'selectionchange' event, and even after throttling it's still happening at least twice

there's an MVP pushed but yea, I'm still working on this

**Comment by arjenzhou** [comment]
@neaumusic  Please do not get any pressure, I don't mean urging but appreciating.

**Comment by neaucode** [comment]
figured a lot of stuff out, I'm just having trouble publishing with the same url I used before.. hopefully the database gets cleaned up tomorrow

it works great, looking forward to publishing it

**Comment by neaucode** [comment]
@arjenzhou https://addons.mozilla.org/en-US/firefox/addon/selection-highlighter-v2/

finally published! it should work great, please file any issues if you run into them

**Comment by neaucode** [comment]
had some issues with firefox reviewers, they thought eval was for remote source code even though it's from the storage (options) api, and they noticed a paypal tracking pixel, so I removed that and it's back on the store
